package Inventory;



import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alish
 */
public class AppliaancesInfo extends javax.swing.JFrame {

    /**
     * Creates new form shoesInfo
     */
    private ArrayList<FootwearPojo>footwear = new ArrayList();
    DefaultTableModel table;
    private String shoesRange = "EU 25-33";
    public AppliaancesInfo() {
        initComponents();
        date();
        time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        rangeBtnGrp = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shoesInfo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        modelLbl = new javax.swing.JLabel();
        modelTxt = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        catCmbBox = new javax.swing.JComboBox<>();
        categoryLbl = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        brandCmbBox = new javax.swing.JComboBox<>();
        lblQuantity = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        rdBtn2 = new javax.swing.JRadioButton();
        rdBtn3 = new javax.swing.JRadioButton();
        rdBtn1 = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        inputQuantity = new javax.swing.JSpinner();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        sCategoryLbl = new javax.swing.JLabel();
        btnCatSearch = new javax.swing.JButton();
        searchCmbBox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        lblSearchPrice = new javax.swing.JLabel();
        txtSearchPrice = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        menuTop = new javax.swing.JMenuBar();
        fileMenuItm = new javax.swing.JMenu();
        loadFile = new javax.swing.JCheckBoxMenuItem();
        exitSystem = new javax.swing.JCheckBoxMenuItem();
        exitMenuItm = new javax.swing.JMenu();
        manualItem = new javax.swing.JCheckBoxMenuItem();

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Royal Footwear Inventory");
        setBackground(new java.awt.Color(51, 0, 0));
        setLocation(new java.awt.Point(250, 2));
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/logo.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(240, 224, 137));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Footwear Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Felix Titling", 1, 18), new java.awt.Color(0, 101, 64))); // NOI18N

        shoesInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "         Model", "         Name", "        Category", "        Brand", "        Size Range", "        Quantity", "        Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(shoesInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.setBackground(new java.awt.Color(230, 228, 217));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "FOOTWEAR DETAILS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 3, 14), new java.awt.Color(110, 24, 16))); // NOI18N

        modelLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modelLbl.setText("Shoes Model  :");

        modelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTxtActionPerformed(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLbl.setText("Name :");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        catCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buckled", "Slip-On", "Lace-Up", "High-Heeled", "Slippers", "Monk Straps", "Slingback" }));
        catCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catCmbBoxActionPerformed(evt);
            }
        });

        categoryLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        categoryLbl.setText("Category :");

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPrice.setText("Price :");

        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        lblBrand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBrand.setText("Brand :");

        brandCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goldstar", "Caliber", "Nike", "Erke", "Adidas", "PUMA", "Reebok", "Converse", "Dr Martens", "Vans", "FILA" }));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity.setText("Quantity :");

        lblSize.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSize.setText("Size Range :");

        rangeBtnGrp.add(rdBtn2);
        rdBtn2.setText("EU 38-43");
        rdBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn2ActionPerformed(evt);
            }
        });

        rangeBtnGrp.add(rdBtn3);
        rdBtn3.setText("EU 43-49");
        rdBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn3ActionPerformed(evt);
            }
        });

        rangeBtnGrp.add(rdBtn1);
        rdBtn1.setSelected(true);
        rdBtn1.setText("EU 25-33");
        rdBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn1ActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(126, 117, 97));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        inputQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(modelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lblBrand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(brandCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(105, 105, 105))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(categoryLbl)
                        .addGap(18, 18, 18)
                        .addComponent(catCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(238, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblPrice))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdBtn1)
                                .addGap(18, 18, 18)
                                .addComponent(rdBtn2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtn3)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLbl)
                    .addComponent(lblBrand)
                    .addComponent(brandCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdBtn1)
                    .addComponent(rdBtn2)
                    .addComponent(rdBtn3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(inputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 207, 188));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "SEARCH SHOES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 3, 18), new java.awt.Color(0, 119, 79))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(225, 335));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(102, 0, 102), new java.awt.Color(0, 153, 153)));
        jPanel4.setPreferredSize(new java.awt.Dimension(193, 87));

        sCategoryLbl.setBackground(new java.awt.Color(204, 255, 255));
        sCategoryLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sCategoryLbl.setText("Category :");

        btnCatSearch.setBackground(new java.awt.Color(186, 90, 36));
        btnCatSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCatSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnCatSearch.setText("Search");
        btnCatSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatSearchActionPerformed(evt);
            }
        });

        searchCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buckled", "Slip-On", "Lace-Up", "High-Heeled", "Slippers", "Monk Straps", "Slingback" }));
        searchCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCmbBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sCategoryLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCatSearch)
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sCategoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCatSearch)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(199, 167, 168));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(102, 102, 102)));

        btnSearch.setBackground(new java.awt.Color(153, 153, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblSearchPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchPrice.setText("Price :");

        txtSearchPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnSearch)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setForeground(new java.awt.Color(255, 255, 255));

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        menuTop.setBackground(new java.awt.Color(115, 211, 65));

        fileMenuItm.setText("File");

        loadFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        loadFile.setText("Load File");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        fileMenuItm.add(loadFile);

        exitSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exitSystem.setText("Exit");
        exitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitSystemActionPerformed(evt);
            }
        });
        fileMenuItm.add(exitSystem);

        menuTop.add(fileMenuItm);

        exitMenuItm.setText("Help");

        manualItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        manualItem.setText("System Manual");
        manualItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualItemActionPerformed(evt);
            }
        });
        exitMenuItm.add(manualItem);

        menuTop.add(exitMenuItm);

        setJMenuBar(menuTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitSystemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitSystemActionPerformed

    public void date(){
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-DD");
        lblDate.setText("Date: "+df.format(d));
    }
    
    public void time(){
       new Timer(0, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               Date d = new Date();
               SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
               lblTime.setText("Time: " + df.format(d));
           }
       }).start();
            
    }
    
    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
         // TODO add your handling code here:
        try {
            DefaultTableModel table = (DefaultTableModel) shoesInfo.getModel();
            table.setRowCount(0);
            BufferedReader br = new BufferedReader(new FileReader("data.CSV"));
            String row = "";
            while((row = br.readLine()) != null){
                String value[] = row.split(",");
                
                table.addRow(value);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane,"File not found", "Missing",1);
        }catch(IOException ioe){}
    }//GEN-LAST:event_loadFileActionPerformed

    private void modelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void catCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catCmbBoxActionPerformed

    private void rdBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn2ActionPerformed

    private void rdBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn3ActionPerformed

    private void clearAction(){
        // To clear all the existance data of textfield
        modelTxt.setText("");
        nameTxt.setText("");
        priceTxt.setText("");
        catCmbBox.setSelectedIndex(0);
        brandCmbBox.setSelectedIndex(0);
        rdBtn1.setSelected(true);
        inputQuantity.setValue(0);
    }
    
    private void exportToCSV(){
        
        try{
            File file = new File("data.CSV");
            if (!file.isFile()) {
                file.createNewFile();
            }
            FileWriter write = new FileWriter(file);
            for(FootwearPojo d : footwear){
                String Obj[] = {d.getModel_Num(), d.getmName(), d.getCategory(), d.getBrand(), d.getSize(),
                    d.getQuantity(), Integer.toString(d.getPrice())};
                for(int i = 0; i < Obj.length; i++){
                    write.append(Obj[i]);
                    if (i == Obj.length-1){
                        break;
                    }
                    write.append(",");
                }
                write.append("\n");
            }
            write.flush();
            write.close();
        }catch(IOException io){
            JOptionPane.showMessageDialog(rootPane,"IOEexception","Runtime error",0);
        }
    }
    
    
    private static void dataSorting(ArrayList<Inventory.FootwearPojo>list){
        /*
        Dividing each data on basis of price
        call megreSort for storing sorted data on table
        */
        if(list.size()<=1)
            return;
        ArrayList<Inventory.FootwearPojo>store1 = new ArrayList();
        ArrayList<Inventory.FootwearPojo>store2 = new ArrayList();
        
        for(int i=0;i<list.size()/2;i++){
            store1.add(list.get(i));
        }
        
        for(int i=0;i<list.size()-store1.size();i++){
            store2.add(list.get(store1.size()+i));
        }
        
        dataSorting(store1);
        dataSorting(store2);
        
        mergeSort(store1, store2, list);
    }
    
    private static void mergeSort(ArrayList<Inventory.FootwearPojo>store1,ArrayList<Inventory.FootwearPojo>store2,ArrayList<Inventory.FootwearPojo>list){
        //Merging the sorted data came from dataSorting method
        int iStore1 = 0;
        int iStore2 = 0;
        int j = 0;
        
        while(iStore1<store1.size() && iStore2<store2.size()){
            if(store1.get(iStore1).getPrice()<store2.get(iStore2).getPrice()){
                list.set(j, store1.get(iStore1));
                iStore1++;
            }else{
                list.set(j, store2.get(iStore2));
                iStore2++;
            }
            j++; 
        }
        while(iStore1<store1.size()){
            list.set(j,store1.get(iStore1));
            iStore1++;
            j++;
        }
        while(iStore2<store2.size()){
            list.set(j,store2.get(iStore2));
            iStore2++;
            j++;
        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String model_Num = modelTxt.getText().trim();
        String mName = nameTxt.getText().trim();
        String tprice = priceTxt.getText().trim();
        String category = catCmbBox.getSelectedItem().toString();
        String brand = brandCmbBox.getSelectedItem().toString();
        String size = "";
        String quantity = inputQuantity.getValue().toString();
        int price=0;
        
        if(rdBtn1.isSelected()){
            size = "EU 25-33";
        }else if (rdBtn2.isSelected()){
            size = "EU 38-43";
        }else{
            size = "EU 43-49";
        }
        
        if(model_Num.equals("") || mName.equals("") || tprice.equals("")){
            JOptionPane.showMessageDialog(this,"Please fill all the fields","Error",0);
        }else{
            if((inputQuantity.getValue().toString()).equals("0")){
                    JOptionPane.showMessageDialog(this,"Items cannot be added with zero quantity.","Quantity error",0);
                    return;
            }
            if(Pattern.compile("[A-Z][a-z]*").matcher(mName).matches()){
                try {
                    price = Integer.parseInt(tprice);
                } catch (NumberFormatException ae) {
                    JOptionPane.showMessageDialog(this, "Enter valid input for price","Error price",0);
                    return;
                }

                int rowCount = shoesInfo.getRowCount();
                int nextRow = 0;
                boolean emptyRow = false;
                String s;
                do {
                    s = (String) shoesInfo.getValueAt(nextRow, 0);
                    if (s != null && s.length() != 0) {
                        nextRow++;
                    } else {
                        emptyRow = true;
                    }
                } while (nextRow < rowCount && !emptyRow);

                if (emptyRow) {
                    int colCount = shoesInfo.getColumnCount();
                    String[] value = {model_Num, mName, category, brand, size, quantity, Integer.toString(price)};

                    FootwearPojo detail = new FootwearPojo(model_Num, mName, price, category, brand, size, quantity);
                    footwear.add(detail);
                    int confrim = JOptionPane.showConfirmDialog(this, "Are you sure?\nDo you want to add this items.",
                            "confirm Details", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (confrim == JOptionPane.YES_OPTION) {
                        //dataSorting(footwear);
                        for (int i = 0; i < colCount; i++) {
                            shoesInfo.setValueAt(value[i], nextRow, i);
                            dataSorting(footwear);
                            exportToCSV();
                            clearAction();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Empty Row not found", "Error", 0);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid name for Shoes", "Error name", 0);
            }
        }
           
    }//GEN-LAST:event_btnAddActionPerformed

    private static int binarySearch(ArrayList<FootwearPojo>footwear,int low, int high, int value){
        
        if(low<=high){
            int betw = (low+high)/2;
            if(footwear.get(betw).getPrice()== value){
                return betw;
            }else if(footwear.get(betw).getPrice() > value){
                return binarySearch(footwear, low, betw-1, value);
            }else{
                return binarySearch(footwear, betw+1, high, value);
            }
        }else{
            return -1;
        }
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txtSearchPrice.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please input price for shoes","Shoes details",0);
        }else{
            try{
                int value = Integer.parseInt(txtSearchPrice.getText().trim());
                
                dataSorting(footwear);
                int index = binarySearch(footwear, 0, footwear.size()-1, value);
                
                int Sconfrim = JOptionPane.showConfirmDialog(this,"Are you sure?\nYou want to search  shoes of price "
                     +txtSearchPrice.getText()+".","confirm Details",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (Sconfrim == JOptionPane.YES_OPTION){
                    if (index == -1) {
                        JOptionPane.showMessageDialog(this, "Sorry !!\n Item searched is found no where in database.",
                                "Sorry !!", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(rootPane,
                                "Ohh !! This is your Searched Information \n"
                                + "\n Shoes Model : " + footwear.get(index).getModel_Num()
                                + "\n Name : " + footwear.get(index).getmName()
                                + "\n Category : " + footwear.get(index).getCategory()
                                + "\n Brand : " + footwear.get(index).getBrand()
                                + "\n Size : " + footwear.get(index).getSize()
                                + "\n Quantity : " + footwear.get(index).getQuantity()
                                + "\n Price : " + footwear.get(index).getPrice(),
                                "Searched Success", 1);
                    }
                    txtSearchPrice.setText("");
                }
            }catch(NumberFormatException cd){
                JOptionPane.showMessageDialog(this,"Invalid input for price","Unreachable price",0);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rdBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn1ActionPerformed
        // TODO add your handling code here:
        shoesRange = "EU 25-33";
    }//GEN-LAST:event_rdBtn1ActionPerformed

    private void searchCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCmbBoxActionPerformed

    private void btnCatSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatSearchActionPerformed
        // TODO add your handling code here:
        String searchCateg ="";
        String category = searchCmbBox.getSelectedItem().toString();
        
        ArrayList<FootwearPojo> search = new ArrayList();
        for(FootwearPojo Obj: footwear){
            if(Obj.getCategory().equals(category)){
                search.add(Obj);
            }
        }
        if(0 !=search.size()){
            for(FootwearPojo z: search){
                searchCateg += "\nShoes Model :" +z.getModel_Num()+
                        "\nBrand :" +z.getBrand()+
                        "\nSize :"+z.getSize()+
                        "\nQuantity :"+z.getQuantity()+"\n";
            }
        }
        if(!searchCateg.equals("")){
            JOptionPane.showMessageDialog(rootPane, "This is your searched category.\n"+searchCateg,"Searched success",1);
            searchCmbBox.setSelectedIndex(0);
            
        }else{
            JOptionPane.showMessageDialog(rootPane,"No Items found under "+category,"Unrechable item",1);
            searchCmbBox.setSelectedIndex(0);
        }        
    }//GEN-LAST:event_btnCatSearchActionPerformed

    private void txtSearchPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchPriceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // To delete the selected data from the table
        
        table =(DefaultTableModel)shoesInfo.getModel();
        try{
            int SelectedRowIndex = shoesInfo.getSelectedRow();
           int remove = JOptionPane.showConfirmDialog(this,"Are you sure?\nDo you want to remove the selected items.",
                       "Remove Details",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
           if(remove == JOptionPane.YES_OPTION){
             table.removeRow(SelectedRowIndex);
           }
        }catch(Exception qn){
            JOptionPane.showMessageDialog(this,"Please Select shoes detail to remove.","Unable to delete",0);
        }       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void manualItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualItemActionPerformed
        // TODO add your handling code here:
         try {
            File help = new File("src\\manual.pdf");
            Desktop.getDesktop().open(help);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_manualItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliaancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliaancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliaancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliaancesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppliaancesInfo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brandCmbBox;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCatSearch;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> catCmbBox;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JMenu exitMenuItm;
    private javax.swing.JCheckBoxMenuItem exitSystem;
    private javax.swing.JMenu fileMenuItm;
    private javax.swing.JSpinner inputQuantity;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSearchPrice;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTime;
    private javax.swing.JCheckBoxMenuItem loadFile;
    private javax.swing.JCheckBoxMenuItem manualItem;
    private javax.swing.JMenuBar menuTop;
    private javax.swing.JLabel modelLbl;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.ButtonGroup rangeBtnGrp;
    private javax.swing.JRadioButton rdBtn1;
    private javax.swing.JRadioButton rdBtn2;
    private javax.swing.JRadioButton rdBtn3;
    private javax.swing.JLabel sCategoryLbl;
    private javax.swing.JComboBox<String> searchCmbBox;
    private javax.swing.JTable shoesInfo;
    private javax.swing.JTextField txtSearchPrice;
    // End of variables declaration//GEN-END:variables
}
